package almar.ventanas;

import almar.controlador.EmpleadoController;
import almar.excepciones.BussinessException;
import almar.excepciones.BussinessMessage;
import almar.entidades.Empleado;
import hibernate.util.HibernateUtil;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import patronObserver.Subject;

/**
 *
 * @author Alberto
 */
public class VentanaEmpleados extends javax.swing.JDialog implements patronObserver.Observer {

    private EmpleadoController empleadoController;
    private DefaultListModel listModel;
    private List listaEmpleados;

    /**
     * Creates new form VentanaEmpleados
     */
    public VentanaEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonCancelar.setVisible(false);
        jButtonGuardar.setVisible(false);
        this.empleadoController = new EmpleadoController();
        empleadoController.registerObserver(this);
        listModel = new DefaultListModel();
        actualizarJlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_idEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_Nif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_Apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_Telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_Ciudad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_Provincia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_CP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox_Activo = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(11, 2, 0, 5));

        jLabel1.setText("id Empleado:");
        jPanel2.add(jLabel1);

        jTF_idEmpleado.setEditable(false);
        jTF_idEmpleado.setEnabled(false);
        jPanel2.add(jTF_idEmpleado);

        jLabel2.setText("Nif:");
        jPanel2.add(jLabel2);

        jTF_Nif.setEditable(false);
        jPanel2.add(jTF_Nif);

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3);

        jTF_Nombre.setEditable(false);
        jPanel2.add(jTF_Nombre);

        jLabel4.setText("Apellidos:");
        jPanel2.add(jLabel4);

        jTF_Apellidos.setEditable(false);
        jPanel2.add(jTF_Apellidos);

        jLabel5.setText("Teléfono:");
        jPanel2.add(jLabel5);

        jTF_Telefono.setEditable(false);
        jPanel2.add(jTF_Telefono);

        jLabel6.setText("Dirección:");
        jPanel2.add(jLabel6);

        jTF_Direccion.setEditable(false);
        jPanel2.add(jTF_Direccion);

        jLabel7.setText("Ciudad:");
        jPanel2.add(jLabel7);

        jTF_Ciudad.setEditable(false);
        jPanel2.add(jTF_Ciudad);

        jLabel8.setText("Provincia:");
        jPanel2.add(jLabel8);

        jTF_Provincia.setEditable(false);
        jPanel2.add(jTF_Provincia);

        jLabel9.setText("CP:");
        jPanel2.add(jLabel9);

        jTF_CP.setEditable(false);
        jPanel2.add(jTF_CP);

        jLabel10.setText("Email:");
        jPanel2.add(jLabel10);

        jTF_Email.setEditable(false);
        jPanel2.add(jTF_Email);

        jLabel11.setText("Activo:");
        jPanel2.add(jLabel11);

        jCheckBox_Activo.setEnabled(false);
        jPanel2.add(jCheckBox_Activo);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 340, -1));

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel12.setText("Lista de Empleados");

        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(9, 9, 9)
                                .addComponent(btnSiguiente))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 310));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonNuevo)
                .addGap(30, 30, 30)
                .addComponent(jButtonModificar)
                .addGap(32, 32, 32)
                .addComponent(jButtonEliminar)
                .addGap(31, 31, 31)
                .addComponent(jButtonGuardar)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 550, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (jList1.getSelectedIndex() > 0) {
            jList1.setSelectedIndex(jList1.getSelectedIndex() - 1);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (jList1.getSelectedIndex() != jList1.getLastVisibleIndex()) {
            jList1.setSelectedIndex(jList1.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarJlist();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        activarCampos(true);
        limpiarCampos();
        jButtonCancelar.setVisible(true);
        jButtonGuardar.setVisible(true);
        jButtonNuevo.setVisible(false);
        jButtonEliminar.setVisible(false);
        jButtonModificar.setVisible(false);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            Empleado empleado;
            if (jTF_idEmpleado.getText().isEmpty()) {//Si es nuevo no lleva id porque se crea autoincrement en la bd:
                empleado = new Empleado(jTF_Nif.getText(), jTF_Nombre.getText(), jTF_Apellidos.getText(), jTF_Telefono.getText(), jTF_Direccion.getText(), jTF_Ciudad.getText(), jTF_Provincia.getText(), jTF_CP.getText(), jTF_Email.getText(), jCheckBox_Activo.isSelected(), null, null);

            } else {//Si es actualización lleva el id:
                empleado = new Empleado(Integer.parseInt(jTF_idEmpleado.getText()), jTF_Nif.getText(), jTF_Nombre.getText(), jTF_Apellidos.getText(), jTF_Telefono.getText(), jTF_Direccion.getText(), jTF_Ciudad.getText(), jTF_Provincia.getText(), jTF_CP.getText(), jTF_Email.getText(), jCheckBox_Activo.isSelected());
            }
            empleadoController.guardar(empleado);
            jButtonCancelar.setVisible(false);
            jButtonGuardar.setVisible(false);
            jButtonModificar.setVisible(true);
            jButtonNuevo.setVisible(true);
            jButtonEliminar.setVisible(true);
            activarCampos(false);
        } catch (BussinessException be) {
            for (BussinessMessage bussinessMessage : be.getBussinessMessages()) {
                JOptionPane.showMessageDialog(null, bussinessMessage.toString());
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if (jTF_idEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun empleado de la lista");
        } else {
            activarCampos(true);
            jButtonCancelar.setVisible(true);
            jButtonGuardar.setVisible(true);
            jButtonModificar.setVisible(false);
            jButtonNuevo.setVisible(false);
            jButtonEliminar.setVisible(false);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (jList1.isSelectionEmpty()) {
            limpiarCampos();
        } else {
            Empleado empleadoSelec = (Empleado) listaEmpleados.get(jList1.getSelectedIndex());
            jTF_idEmpleado.setText(empleadoSelec.getIdEmpleado().toString());
            jTF_Nif.setText(empleadoSelec.getNif());
            jTF_Nombre.setText(empleadoSelec.getNombre());
            jTF_Apellidos.setText(empleadoSelec.getApellidos());
            jTF_Telefono.setText(empleadoSelec.getTelefono());
            jTF_Direccion.setText(empleadoSelec.getDireccion());
            jTF_Ciudad.setText(empleadoSelec.getCiudad());
            jTF_Provincia.setText(empleadoSelec.getProvincia());
            jTF_CP.setText(empleadoSelec.getCp());
            jTF_Email.setText(empleadoSelec.getEmail());
            jCheckBox_Activo.setSelected(empleadoSelec.isEstado());
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        try {
            if (jTF_idEmpleado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun empleado de la lista");
            } else {
                int i = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que quiere eliminar a ese empleado?", "Eliminar Empleado", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (i == 0) {
                    empleadoController.eliminarPorId(Integer.parseInt(jTF_idEmpleado.getText()));
                }
            }
        } catch (BussinessException be) {
            for (BussinessMessage bussinessMessage : be.getBussinessMessages()) {
                JOptionPane.showMessageDialog(null, bussinessMessage.toString());
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        activarCampos(false);
        jList1ValueChanged(null);//Vuelve a poner en los campos el valor selecionado del jList.
        jButtonCancelar.setVisible(false);
        jButtonGuardar.setVisible(false);
        jButtonModificar.setVisible(true);
        jButtonNuevo.setVisible(true);
        jButtonEliminar.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void actualizarJlist() {
        HibernateUtil.openSessionAndBindToThread();
        try {
            listModel.clear();
            listaEmpleados = empleadoController.listaEmpleados();
            Iterator<Empleado> i = listaEmpleados.iterator();
            Empleado temp;
            while (i.hasNext()) {
                temp = i.next();
                listModel.addElement(temp.getNombre() + " " + temp.getApellidos());
            }
            jList1.setModel(listModel);
        } catch (BussinessException be) {
            for (BussinessMessage bussinessMessage : be.getBussinessMessages()) {
                JOptionPane.showMessageDialog(null, bussinessMessage.toString());
            }
        } finally {
            HibernateUtil.closeSessionAndUnbindFromThread();
        }
    }

    private void activarCampos(boolean estado) {
        for (Object obj : jPanel2.getComponents()) {
            if (obj instanceof JTextField) {
                JTextField temp = (JTextField) obj;
                if (temp != jTF_idEmpleado) {//El campo del id no quiero que se active.
                    temp.setEditable(estado);
                }
            }
            if (obj instanceof JCheckBox) {
                JCheckBox temp = (JCheckBox) obj;
                temp.setEnabled(estado);
            }
        }
    }

    private void limpiarCampos() {
        for (Object obj : jPanel2.getComponents()) {
            if (obj instanceof JTextField) {
                JTextField temp = (JTextField) obj;
                temp.setText(null);
            }
            if (obj instanceof JCheckBox) {
                JCheckBox temp = (JCheckBox) obj;
                temp.setSelected(false);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaEmpleados dialog = new VentanaEmpleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JCheckBox jCheckBox_Activo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Apellidos;
    private javax.swing.JTextField jTF_CP;
    private javax.swing.JTextField jTF_Ciudad;
    private javax.swing.JTextField jTF_Direccion;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_Nif;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_Provincia;
    private javax.swing.JTextField jTF_Telefono;
    private javax.swing.JTextField jTF_idEmpleado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Subject subject) {
        if (subject instanceof EmpleadoController) {
            actualizarJlist();
        }
    }
}
