package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Byte idArticulo;
     private Categoria categoria;
     private Proveedor proveedor;
     private String codFabricante;
     private byte stock;
     private String nombre;
     private int precio;
     private String descripcion;
     private Set lineasPedidos = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(Categoria categoria, Proveedor proveedor, byte stock, String nombre, int precio) {
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Articulo(Categoria categoria, Proveedor proveedor, String codFabricante, byte stock, String nombre, int precio, String descripcion, Set lineasPedidos) {
       this.categoria = categoria;
       this.proveedor = proveedor;
       this.codFabricante = codFabricante;
       this.stock = stock;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcion = descripcion;
       this.lineasPedidos = lineasPedidos;
    }
   
    public Byte getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Byte idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getCodFabricante() {
        return this.codFabricante;
    }
    
    public void setCodFabricante(String codFabricante) {
        this.codFabricante = codFabricante;
    }
    public byte getStock() {
        return this.stock;
    }
    
    public void setStock(byte stock) {
        this.stock = stock;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getLineasPedidos() {
        return this.lineasPedidos;
    }
    
    public void setLineasPedidos(Set lineasPedidos) {
        this.lineasPedidos = lineasPedidos;
    }




}


