package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Byte idCliente;
     private String nif;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String email;
     private String direccion;
     private String provincia;
     private String cp;
     private String ciudad;
     private Set pedidos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nif, String nombre, String apellidos, String telefono, String direccion) {
        this.nif = nif;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.direccion = direccion;
    }
    public Cliente(String nif, String nombre, String apellidos, String telefono, String email, String direccion, String provincia, String cp, String ciudad, Set pedidos) {
       this.nif = nif;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.provincia = provincia;
       this.cp = cp;
       this.ciudad = ciudad;
       this.pedidos = pedidos;
    }
   
    public Byte getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Byte idCliente) {
        this.idCliente = idCliente;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


