package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Byte idFormaPago;
     private String descripcion;
     private Set pedidos = new HashSet(0);

    public FormaPago() {
    }

	
    public FormaPago(String descripcion) {
        this.descripcion = descripcion;
    }
    public FormaPago(String descripcion, Set pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
    public Byte getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(Byte idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


