package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1



/**
 * LineasPedido generated by hbm2java
 */
public class LineasPedido  implements java.io.Serializable {


     private LineasPedidoId id;
     private Articulo articulo;
     private Pedido pedido;
     private byte numArticulos;

    public LineasPedido() {
    }

    public LineasPedido(LineasPedidoId id, Articulo articulo, Pedido pedido, byte numArticulos) {
       this.id = id;
       this.articulo = articulo;
       this.pedido = pedido;
       this.numArticulos = numArticulos;
    }
   
    public LineasPedidoId getId() {
        return this.id;
    }
    
    public void setId(LineasPedidoId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public byte getNumArticulos() {
        return this.numArticulos;
    }
    
    public void setNumArticulos(byte numArticulos) {
        this.numArticulos = numArticulos;
    }




}


