package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Byte idPedido;
     private Cliente cliente;
     private Empleado empleado;
     private FormaPago formaPago;
     private Date fecha;
     private int total;
     private boolean presupuesto;
     private boolean pagado;
     private Set lineasPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, Empleado empleado, FormaPago formaPago, Date fecha, int total, boolean presupuesto, boolean pagado) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.formaPago = formaPago;
        this.fecha = fecha;
        this.total = total;
        this.presupuesto = presupuesto;
        this.pagado = pagado;
    }
    public Pedido(Cliente cliente, Empleado empleado, FormaPago formaPago, Date fecha, int total, boolean presupuesto, boolean pagado, Set lineasPedidos) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.formaPago = formaPago;
       this.fecha = fecha;
       this.total = total;
       this.presupuesto = presupuesto;
       this.pagado = pagado;
       this.lineasPedidos = lineasPedidos;
    }
   
    public Byte getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Byte idPedido) {
        this.idPedido = idPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }
    public boolean isPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(boolean presupuesto) {
        this.presupuesto = presupuesto;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }
    public Set getLineasPedidos() {
        return this.lineasPedidos;
    }
    
    public void setLineasPedidos(Set lineasPedidos) {
        this.lineasPedidos = lineasPedidos;
    }




}


