package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Byte idProveedor;
     private String cif;
     private String nombre;
     private String telefono;
     private String email;
     private String direccion;
     private String provincia;
     private String ciudad;
     private String cp;
     private Set articulos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String cif, String nombre, String telefono, String direccion) {
        this.cif = cif;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
    }
    public Proveedor(String cif, String nombre, String telefono, String email, String direccion, String provincia, String ciudad, String cp, Set articulos) {
       this.cif = cif;
       this.nombre = nombre;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.provincia = provincia;
       this.ciudad = ciudad;
       this.cp = cp;
       this.articulos = articulos;
    }
   
    public Byte getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Byte idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


