package almar.entity;
// Generated 28-ene-2015 14:00:51 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Byte idUsuario;
     private Empleado empleado;
     private String nombre;
     private String password;
     private String permisos;

    public Usuario() {
    }

    public Usuario(Empleado empleado, String nombre, String password, String permisos) {
       this.empleado = empleado;
       this.nombre = nombre;
       this.password = password;
       this.permisos = permisos;
    }
   
    public Byte getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Byte idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(String permisos) {
        this.permisos = permisos;
    }




}


