package almar.entidades;
// Generated 05-feb-2015 0:39:43 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo implements java.io.Serializable {

    private Integer idArticulo;
    private Categoria categoria;
    private Proveedor proveedor;
    private String codFabricante;
    private int stock;
    private String nombre;
    private int precio;
    private String descripcion;
    private Set lineasPedidos = new HashSet(0);

    public Articulo() {
    }

    public Articulo(Categoria categoria, Proveedor proveedor, int stock, String nombre, int precio) {
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
    }

    public Articulo(Categoria categoria, Proveedor proveedor, String codFabricante, int stock, String nombre, int precio, String descripcion, Set lineasPedidos) {
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.codFabricante = codFabricante;
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
        this.descripcion = descripcion;
        this.lineasPedidos = lineasPedidos;
    }

    public Articulo(Integer idArticulo, Categoria categoria, Proveedor proveedor, String codFabricante, int stock, String nombre, int precio, String descripcion) {
        this.idArticulo = idArticulo;
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.codFabricante = codFabricante;
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
        this.descripcion = descripcion;
    }

    public Integer getIdArticulo() {
        return this.idArticulo;
    }

    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Proveedor getProveedor() {
        return this.proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    public String getCodFabricante() {
        return this.codFabricante;
    }

    public void setCodFabricante(String codFabricante) {
        this.codFabricante = codFabricante;
    }

    public int getStock() {
        return this.stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getPrecio() {
        return this.precio;
    }

    public void setPrecio(int precio) {
        this.precio = precio;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getLineasPedidos() {
        return this.lineasPedidos;
    }

    public void setLineasPedidos(Set lineasPedidos) {
        this.lineasPedidos = lineasPedidos;
    }

    @Override
    public String toString() {
        return "Articulo{" + "idArticulo=" + idArticulo + ", categoria=" + categoria + ", proveedor=" + proveedor + ", codFabricante=" + codFabricante + ", stock=" + stock + ", nombre=" + nombre + ", precio=" + precio + ", descripcion=" + descripcion + ", lineasPedidos=" + lineasPedidos + '}';
    }

}
