package almar.entidades;
// Generated 05-feb-2015 0:39:43 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.Size;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago implements java.io.Serializable {

    private Integer idFormaPago;
    @Size(min = 3, max = 40)
    private String descripcion;
    private Set pedidos = new HashSet(0);

    public FormaPago() {
    }

    public FormaPago(String descripcion) {
        this.descripcion = descripcion;
    }

    public FormaPago(String descripcion, Set pedidos) {
        this.descripcion = descripcion;
        this.pedidos = pedidos;
    }

    public FormaPago(Integer idFormaPago, String descripcion) {
        this.idFormaPago = idFormaPago;
        this.descripcion = descripcion;
    }

    public Integer getIdFormaPago() {
        return this.idFormaPago;
    }

    public void setIdFormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getPedidos() {
        return this.pedidos;
    }

    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public String toString() {
        return "FormaPago{" + "idFormaPago=" + idFormaPago + ", descripcion=" + descripcion + ", pedidos=" + pedidos + '}';
    }

}
