package almar.entidades;
// Generated 05-feb-2015 0:39:43 by Hibernate Tools 4.3.1

import javax.validation.constraints.Min;


/**
 * LineasPedido generated by hbm2java
 */
public class LineasPedido implements java.io.Serializable {

    private LineasPedidoId id;
    private Articulo articulo;
    private Pedido pedido;
    @Min(1)
    private int numArticulos;

    public LineasPedido() {
    }

    public LineasPedido(LineasPedidoId id, Articulo articulo, Pedido pedido, int numArticulos) {
        this.id = id;
        this.articulo = articulo;
        this.pedido = pedido;
        this.numArticulos = numArticulos;
    }

    public LineasPedidoId getId() {
        return this.id;
    }

    public void setId(LineasPedidoId id) {
        this.id = id;
    }

    public Articulo getArticulo() {
        return this.articulo;
    }

    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    public Pedido getPedido() {
        return this.pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public int getNumArticulos() {
        return this.numArticulos;
    }

    public void setNumArticulos(int numArticulos) {
        this.numArticulos = numArticulos;
    }

    @Override
    public String toString() {
        return "LineasPedido{" + "id=" + id + ", articulo=" + articulo + ", pedido=" + pedido + ", numArticulos=" + numArticulos + '}';
    }

}
